# Rubya Akter Badhon 

# Font

font_family      Fira Code
bold_font        Fira Code Bold
italic_font      Fira Code Italic
bold_italic_font Fira Code Bold Italic

#  14" screen -- 11
#  16" screen -- 13
            
font_size 13

# Theme

# background_opacity 0.8

# background     #000000
foreground     #bdc1c6
# background     #09051a
cursor         #9ca1aa
color1   #1d3b53
color2   #fc514e
color3   #a1cd5e
color4   #0d7bbf
color5   #82aaff
color6   #c792ea
color7   #7fdbca	
color8   #a1aab8
color9   #7c8f8f
color10  #ff5874	
color11  #21c7a8	
color12  #ecc48d	
color13  #82aaff	
color14  #ae81ff
color15  #7fdbca	
color16  #d6deeb			

background_image ~/Pictures/wallpapers/terminal.jpg
background_image_layout tiled

# Mouse

mouse_hide_wait 1.0

# url

url_color #0087bd
url_style curly
open_url_with default

# window

window_logo_position bottom-right
remember_window_size  no
enabled_layouts tall

# Keyboard Bindings

map ctrl+shift+w	launch
map ctrl+shift+n	next_window
map ctrl+shift+p	previous_window
map ctrl+shift+f	move_window_forward
map ctrl+shift+b	move_window_backward
map ctrl+shift+left	resize_window narrower
map ctrl+shift+right	resize_window wider
map ctrl+shift+up	resize_window taller
map ctrl+shift+down	resize_window shorter
map ctrl+shift+q        close_window
